backend:
  name: git-gateway
  branch: master

media_folder: static/images
public_folder: ../../static/images/

slug:
  encoding: "ascii"
  clean_accents: true

collections:
  - name: 'pesme'
    preview: false
    label: 'Pesme'
    folder: 'content/pesme'
    create: true
    slug: '{{slug}}'
    fields:
      - {label: 'Naslov', name: 'title', widget: 'string'}
      - {label: 'Datum', name: 'date', widget: 'date'}
      - {label: 'Objavljeno', name: 'objavljeno', widget: 'string', required: false}
      - {label: 'Pesma', name: 'body', widget: 'text'}

  - name: 'poruke'
    preview: false
    label: 'Poruke'
    folder: 'content/poruke'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Pisac', name: 'title', widget: 'string' }
      - { label: 'Poruka', name: 'body', widget: 'text' }